In [74]:
#Import your libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn import datasets
from sklearn.datasets import make_regression
from sklearn.model_selection import train_test_split
import pickle
import joblib

from sklearn import linear_model
from sklearn.linear_model import ElasticNet
from sklearn.linear_model import Ridge
from sklearn.svm import SVR
from sklearn.linear_model import SGDRegressor
from sklearn.linear_model import LinearRegression

### Exploración de los datos

In [75]:
#importamos todos los datos

di_city = pd.read_csv("./data/diamonds_city_202208201409.csv", keep_default_na=False, na_values=[""])
di_clarity = pd.read_csv("./data/diamonds_clarity_202208201409.csv", keep_default_na=False, na_values=[""])
di_color = pd.read_csv("./data/diamonds_color_202208201409.csv", keep_default_na=False, na_values=[""])
di_cut = pd.read_csv("./data/diamonds_cut_202208201409.csv", keep_default_na=False, na_values=[""])
di_dime = pd.read_csv("./data/diamonds_dimensions_202208201409.csv", keep_default_na=False, na_values=[""])
di_prop = pd.read_csv("./data/diamonds_properties_202208201409.csv", keep_default_na=False, na_values=[""])
di_trans = pd.read_csv("./data/diamonds_transactional_202208201409.csv", keep_default_na=False, na_values=[""])

In [76]:
#vemos cómo son y la información que trae cada tabala- esta es de las ciudades
di_city.info()
di_city

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   city_id  13 non-null     object
 1   city     13 non-null     object
dtypes: object(2)
memory usage: 336.0+ bytes

                                              city_id           city
0   0013c01fe0d094209b8bd3d23b8f96dbabcd01ddd2a039...      Amsterdam
1   1e73b1647343b286269d517e6f07e6e07ccef10cd7b785...         Zurich
2   2bd25cd960aba8b706e2b67f2bb38b750ee5384b0e9883...      Las Vegas
3   5a59ef2e40c5f89adb8c0c6ad0a8019b0e252fff530cf2...  New York City
4   5dd272b4f316b776a7b8e3d0894b37e1e42be3d5d3b204...          Paris
5   68371d5bdaab31b5cbc25fbf94b8f9c1238294fc50e715...       Tel Aviv
6   6c425048aa7badd9d84615bd8620ca1864efd81cfdb69d...          Dubai
7   89c7286890f7347ab235234e74d406596a127ae3679042...       Kimberly
8   ba04d229e496b8383a4df91f5e77c194a95cf1a069b0b2...          Surat
9   ca3aa21a5b70c3e88cc6336682c8c7da928a0c66a5ead4...        Antwerp
10  e9c722cbefc2f055ae60b4e2cbe73a2d99537eab0c37f3...         Madrid
11  ecc0e7dc084f141b29479058967d0bc07dee25d9690a98...         London
12  ed76f191621cf6ed77eab6a8013d1cb4bdfa89a75a24aa...     Luxembourg

In [77]:
#vemos cómo son y la información que trae cada tabala- esta es de clarity

di_clarity.info()
di_clarity

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   clarity_id  8 non-null      object
 1   clarity     8 non-null      object
dtypes: object(2)
memory usage: 256.0+ bytes

                                          clarity_id clarity
0  03c358cbd92e83278fd523f58dc6a9b4b198d00728af65...     SI2
1  3f9db06236e9719b61c826b612b882fa702ec81574e44c...    VVS2
2  66686ae1f0c9c400ba32dc600a34ff0aa173395bcbc2d8...    VVS1
3  7020fd7aaf1656dea5c0c0c3d4bb5a28ebf6243fba95d3...      IF
4  bd4f4a250da88f87729febc739ae97f439a14f9d38f0e3...     SI1
5  c2818bc4e5ec4ae4a357a0df6fed73652e169ec676f7d4...      I1
6  ef736c1f91cd1900c3d9cde925b1bf4f013adc0211a9ee...     VS1
7  f0b2a1d0db08cc64f85d74f1d15c2191e0e49039f4d8f2...     VS2

In [78]:
#vemos cómo son y la información que trae cada tabala- esta es de los colores de los diamantes

di_color.info()
di_color

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   color_id  7 non-null      object
 1   color     7 non-null      object
dtypes: object(2)
memory usage: 240.0+ bytes

                                            color_id color
0  333e0a1e27815d0ceee55c473fe3dc93d56c63e3bee2b3...     G
1  3f39d5c348e5b79d06e842c114e6cc571583bbf44e4b0e...     D
2  44bd7ae60f478fae1061e11a7739f4b94d1daf917982d3...     H
3  6da43b944e494e885e69af021f93c6d9331c78aa228084...     J
4  a83dd0ccbffe39d071cc317ddf6e97f5c6b1c87af91919...     I
5  a9f51566bd6705f7ea6ad54bb9deb449f795582d6529a0...     E
6  f67ab10ad4e4c53121b6a5fe4da9c10ddee905b978d378...     F

In [79]:
#vemos cómo son y la información que trae cada tabala- esta es la del tipo de corte

di_cut.info()
di_cut

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   cut_id  5 non-null      object
 1   cut     5 non-null      object
dtypes: object(2)
memory usage: 208.0+ bytes

                                              cut_id        cut
0  388655e25e91872329272fc10128ef5354b3b19a05d7e8...  Very Good
1  4e3cfaa334cbafb57a399a98fad8d3812ece460018f457...      Ideal
2  c939327ca16dcf97ca32521d8b834bf1de16573d21deda...       Good
3  de88c121a82a06352bf1aaceba20578356408a334ba046...    Premium
4  f7b19afcde965ea4942b878d266f89f8ba9a5a833e60f7...       Fair

In [80]:
#vemos cómo son y la información que trae cada tabala- esta es de las dimensiones
di_dime.info()
di_dime

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40455 entries, 0 to 40454
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   index_id  40455 non-null  object
 1   depth     40455 non-null  float64
 2   table     40455 non-null  float64
 3   x         40455 non-null  float64
 4   y         40455 non-null  float64
 5   z         40455 non-null  float64
dtypes: float64(5), object(1)
memory usage: 1.9+ MB

,index_id,depth,table,x,y,z
0,5feceb66ffc86f38d952786c6d696c79c2dbc239dd4e91...,62.4,58.0,6.83,6.79,4.25
1,6b86b273ff34fce19d6b804eff5a3f5747ada4eaa22f1d...,63.0,57.0,4.35,4.38,2.75
2,d4735e3a265e16eee03f59718b9b5d03019c07d8b6c51f...,65.5,55.0,5.62,5.53,3.65
3,4e07408562bedb8b60ce05c1decfe3ad16b72230967de0...,63.8,56.0,4.68,4.72,3.00
4,4b227777d4dd1fc61c6f884f48641d02b4d121d3fd328c...,60.5,59.0,6.55,6.51,3.95
...,...,...,...,...,...,...
40450,f0bc79169405ebeb24e308055156b946ffd819db9b4f75...,62.7,57.0,7.10,7.04,4.43
40451,339916a23bf22b052b54cb2a9b36ee8418c1c68b46acad...,57.1,60.0,8.31,8.25,4.73
40452,46957922b99954654c1deb8d854c3f069bf118b2ce9415...,62.7,56.0,6.37,6.42,4.01
40453,9d733392d362d5c6f1d9b9659b601c7d4b5a1c1c8df579...,61.9,54.3,4.45,4.47,2.76
40454,a02744a70faa594d240b067f21fcc23a8d17cd1098a9fb...,62.0,58.0,6.83,6.88,4.25

In [81]:
#vemos cómo son y la información que trae cada tabala- esta es de las proporciones

di_prop.info()
di_prop

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40455 entries, 0 to 40454
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   index_id    40455 non-null  object
 1   cut_id      40455 non-null  object
 2   color_id    40455 non-null  object
 3   clarity_id  40455 non-null  object
dtypes: object(4)
memory usage: 1.2+ MB

,index_id,cut_id,color_id,clarity_id
0,5feceb66ffc86f38d952786c6d696c79c2dbc239dd4e91...,de88c121a82a06352bf1aaceba20578356408a334ba046...,6da43b944e494e885e69af021f93c6d9331c78aa228084...,f0b2a1d0db08cc64f85d74f1d15c2191e0e49039f4d8f2...
1,6b86b273ff34fce19d6b804eff5a3f5747ada4eaa22f1d...,388655e25e91872329272fc10128ef5354b3b19a05d7e8...,44bd7ae60f478fae1061e11a7739f4b94d1daf917982d3...,f0b2a1d0db08cc64f85d74f1d15c2191e0e49039f4d8f2...
2,d4735e3a265e16eee03f59718b9b5d03019c07d8b6c51f...,f7b19afcde965ea4942b878d266f89f8ba9a5a833e60f7...,333e0a1e27815d0ceee55c473fe3dc93d56c63e3bee2b3...,ef736c1f91cd1900c3d9cde925b1bf4f013adc0211a9ee...
3,4e07408562bedb8b60ce05c1decfe3ad16b72230967de0...,c939327ca16dcf97ca32521d8b834bf1de16573d21deda...,3f39d5c348e5b79d06e842c114e6cc571583bbf44e4b0e...,bd4f4a250da88f87729febc739ae97f439a14f9d38f0e3...
4,4b227777d4dd1fc61c6f884f48641d02b4d121d3fd328c...,4e3cfaa334cbafb57a399a98fad8d3812ece460018f457...,333e0a1e27815d0ceee55c473fe3dc93d56c63e3bee2b3...,bd4f4a250da88f87729febc739ae97f439a14f9d38f0e3...
...,...,...,...,...
40450,f0bc79169405ebeb24e308055156b946ffd819db9b4f75...,4e3cfaa334cbafb57a399a98fad8d3812ece460018f457...,333e0a1e27815d0ceee55c473fe3dc93d56c63e3bee2b3...,ef736c1f91cd1900c3d9cde925b1bf4f013adc0211a9ee...
40451,339916a23bf22b052b54cb2a9b36ee8418c1c68b46acad...,c939327ca16dcf97ca32521d8b834bf1de16573d21deda...,f67ab10ad4e4c53121b6a5fe4da9c10ddee905b978d378...,03c358cbd92e83278fd523f58dc6a9b4b198d00728af65...
40452,46957922b99954654c1deb8d854c3f069bf118b2ce9415...,4e3cfaa334cbafb57a399a98fad8d3812ece460018f457...,44bd7ae60f478fae1061e11a7739f4b94d1daf917982d3...,bd4f4a250da88f87729febc739ae97f439a14f9d38f0e3...
40453,9d733392d362d5c6f1d9b9659b601c7d4b5a1c1c8df579...,4e3cfaa334cbafb57a399a98fad8d3812ece460018f457...,6da43b944e494e885e69af021f93c6d9331c78aa228084...,ef736c1f91cd1900c3d9cde925b1bf4f013adc0211a9ee...
40454,a02744a70faa594d240b067f21fcc23a8d17cd1098a9fb...,4e3cfaa334cbafb57a399a98fad8d3812ece460018f457...,a83dd0ccbffe39d071cc317ddf6e97f5c6b1c87af91919...,bd4f4a250da88f87729febc739ae97f439a14f9d38f0e3...

In [82]:
#vemos cómo son y la información que trae cada tabala- esta es de las transacciones

di_trans.info()
di_trans

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40455 entries, 0 to 40454
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   index_id  40455 non-null  object
 1   price     40455 non-null  int64
 2   city_id   40455 non-null  object
 3   carat     40455 non-null  float64
dtypes: float64(1), int64(1), object(2)
memory usage: 1.2+ MB

,index_id,price,city_id,carat
0,5feceb66ffc86f38d952786c6d696c79c2dbc239dd4e91...,4268,89c7286890f7347ab235234e74d406596a127ae3679042...,1.21
1,6b86b273ff34fce19d6b804eff5a3f5747ada4eaa22f1d...,505,ca3aa21a5b70c3e88cc6336682c8c7da928a0c66a5ead4...,0.32
2,d4735e3a265e16eee03f59718b9b5d03019c07d8b6c51f...,2686,ecc0e7dc084f141b29479058967d0bc07dee25d9690a98...,0.71
3,4e07408562bedb8b60ce05c1decfe3ad16b72230967de0...,738,5a59ef2e40c5f89adb8c0c6ad0a8019b0e252fff530cf2...,0.41
4,4b227777d4dd1fc61c6f884f48641d02b4d121d3fd328c...,4882,6c425048aa7badd9d84615bd8620ca1864efd81cfdb69d...,1.02
...,...,...,...,...
40450,f0bc79169405ebeb24e308055156b946ffd819db9b4f75...,10070,5a59ef2e40c5f89adb8c0c6ad0a8019b0e252fff530cf2...,1.34
40451,339916a23bf22b052b54cb2a9b36ee8418c1c68b46acad...,12615,1e73b1647343b286269d517e6f07e6e07ccef10cd7b785...,2.02
40452,46957922b99954654c1deb8d854c3f069bf118b2ce9415...,5457,68371d5bdaab31b5cbc25fbf94b8f9c1238294fc50e715...,1.01
40453,9d733392d362d5c6f1d9b9659b601c7d4b5a1c1c8df579...,456,5dd272b4f316b776a7b8e3d0894b37e1e42be3d5d3b204...,0.33
40454,a02744a70faa594d240b067f21fcc23a8d17cd1098a9fb...,6232,ca3aa21a5b70c3e88cc6336682c8c7da928a0c66a5ead4...,1.24

### Cruce de tablas

In [83]:
#concateno las tres tablas últimas que tienen el mismo número de rows 

df_concat = pd.concat([di_trans, di_dime, di_prop, ], ignore_index=False, axis=1)

In [84]:
df_concat

,index_id,price,city_id,carat,index_id,depth,table,x,y,z,index_id,cut_id,color_id,clarity_id
0,5feceb66ffc86f38d952786c6d696c79c2dbc239dd4e91...,4268,89c7286890f7347ab235234e74d406596a127ae3679042...,1.21,5feceb66ffc86f38d952786c6d696c79c2dbc239dd4e91...,62.4,58.0,6.83,6.79,4.25,5feceb66ffc86f38d952786c6d696c79c2dbc239dd4e91...,de88c121a82a06352bf1aaceba20578356408a334ba046...,6da43b944e494e885e69af021f93c6d9331c78aa228084...,f0b2a1d0db08cc64f85d74f1d15c2191e0e49039f4d8f2...
1,6b86b273ff34fce19d6b804eff5a3f5747ada4eaa22f1d...,505,ca3aa21a5b70c3e88cc6336682c8c7da928a0c66a5ead4...,0.32,6b86b273ff34fce19d6b804eff5a3f5747ada4eaa22f1d...,63.0,57.0,4.35,4.38,2.75,6b86b273ff34fce19d6b804eff5a3f5747ada4eaa22f1d...,388655e25e91872329272fc10128ef5354b3b19a05d7e8...,44bd7ae60f478fae1061e11a7739f4b94d1daf917982d3...,f0b2a1d0db08cc64f85d74f1d15c2191e0e49039f4d8f2...
2,d4735e3a265e16eee03f59718b9b5d03019c07d8b6c51f...,2686,ecc0e7dc084f141b29479058967d0bc07dee25d9690a98...,0.71,d4735e3a265e16eee03f59718b9b5d03019c07d8b6c51f...,65.5,55.0,5.62,5.53,3.65,d4735e3a265e16eee03f59718b9b5d03019c07d8b6c51f...,f7b19afcde965ea4942b878d266f89f8ba9a5a833e60f7...,333e0a1e27815d0ceee55c473fe3dc93d56c63e3bee2b3...,ef736c1f91cd1900c3d9cde925b1bf4f013adc0211a9ee...
3,4e07408562bedb8b60ce05c1decfe3ad16b72230967de0...,738,5a59ef2e40c5f89adb8c0c6ad0a8019b0e252fff530cf2...,0.41,4e07408562bedb8b60ce05c1decfe3ad16b72230967de0...,63.8,56.0,4.68,4.72,3.00,4e07408562bedb8b60ce05c1decfe3ad16b72230967de0...,c939327ca16dcf97ca32521d8b834bf1de16573d21deda...,3f39d5c348e5b79d06e842c114e6cc571583bbf44e4b0e...,bd4f4a250da88f87729febc739ae97f439a14f9d38f0e3...
4,4b227777d4dd1fc61c6f884f48641d02b4d121d3fd328c...,4882,6c425048aa7badd9d84615bd8620ca1864efd81cfdb69d...,1.02,4b227777d4dd1fc61c6f884f48641d02b4d121d3fd328c...,60.5,59.0,6.55,6.51,3.95,4b227777d4dd1fc61c6f884f48641d02b4d121d3fd328c...,4e3cfaa334cbafb57a399a98fad8d3812ece460018f457...,333e0a1e27815d0ceee55c473fe3dc93d56c63e3bee2b3...,bd4f4a250da88f87729febc739ae97f439a14f9d38f0e3...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40450,f0bc79169405ebeb24e308055156b946ffd819db9b4f75...,10070,5a59ef2e40c5f89adb8c0c6ad0a8019b0e252fff530cf2...,1.34,f0bc79169405ebeb24e308055156b946ffd819db9b4f75...,62.7,57.0,7.10,7.04,4.43,f0bc79169405ebeb24e308055156b946ffd819db9b4f75...,4e3cfaa334cbafb57a399a98fad8d3812ece460018f457...,333e0a1e27815d0ceee55c473fe3dc93d56c63e3bee2b3...,ef736c1f91cd1900c3d9cde925b1bf4f013adc0211a9ee...
40451,339916a23bf22b052b54cb2a9b36ee8418c1c68b46acad...,12615,1e73b1647343b286269d517e6f07e6e07ccef10cd7b785...,2.02,339916a23bf22b052b54cb2a9b36ee8418c1c68b46acad...,57.1,60.0,8.31,8.25,4.73,339916a23bf22b052b54cb2a9b36ee8418c1c68b46acad...,c939327ca16dcf97ca32521d8b834bf1de16573d21deda...,f67ab10ad4e4c53121b6a5fe4da9c10ddee905b978d378...,03c358cbd92e83278fd523f58dc6a9b4b198d00728af65...
40452,46957922b99954654c1deb8d854c3f069bf118b2ce9415...,5457,68371d5bdaab31b5cbc25fbf94b8f9c1238294fc50e715...,1.01,46957922b99954654c1deb8d854c3f069bf118b2ce9415...,62.7,56.0,6.37,6.42,4.01,46957922b99954654c1deb8d854c3f069bf118b2ce9415...,4e3cfaa334cbafb57a399a98fad8d3812ece460018f457...,44bd7ae60f478fae1061e11a7739f4b94d1daf917982d3...,bd4f4a250da88f87729febc739ae97f439a14f9d38f0e3...
40453,9d733392d362d5c6f1d9b9659b601c7d4b5a1c1c8df579...,456,5dd272b4f316b776a7b8e3d0894b37e1e42be3d5d3b204...,0.33,9d733392d362d5c6f1d9b9659b601c7d4b5a1c1c8df579...,61.9,54.3,4.45,4.47,2.76,9d733392d362d5c6f1d9b9659b601c7d4b5a1c1c8df579...,4e3cfaa334cbafb57a399a98fad8d3812ece460018f457...,6da43b944e494e885e69af021f93c6d9331c78aa228084...,ef736c1f91cd1900c3d9cde925b1bf4f013adc0211a9ee...
40454,a02744a70faa594d240b067f21fcc23a8d17cd1098a9fb...,6232,ca3aa21a5b70c3e88cc6336682c8c7da928a0c66a5ead4...,1.24,a02744a70faa594d240b067f21fcc23a8d17cd1098a9fb...,62.0,58.0,6.83,6.88,4.25,a02744a70faa594d240b067f21fcc23a8d17cd1098a9fb...,4e3cfaa334cbafb57a399a98fad8d3812ece460018f457...,a83dd0ccbffe39d071cc317ddf6e97f5c6b1c87af91919...,bd4f4a250da88f87729febc739ae97f439a14f9d38f0e3...

In [85]:
#ahora toca juntar el resto de las tablas para poder empezar mergearlas con la tabla creada arriba df_concat(la que hemos concatenado)

In [86]:
#jutnto la de las ciudades con la df_concat

df_join1 = [df_concat, di_city]
df_city = ft.reduce(lambda left, right: pd.merge(left, right, on='city_id'), df_join1)
df_city

,index_id,price,city_id,carat,index_id,depth,table,x,y,z,index_id,cut_id,color_id,clarity_id,city
0,5feceb66ffc86f38d952786c6d696c79c2dbc239dd4e91...,4268,89c7286890f7347ab235234e74d406596a127ae3679042...,1.21,5feceb66ffc86f38d952786c6d696c79c2dbc239dd4e91...,62.4,58.0,6.83,6.79,4.25,5feceb66ffc86f38d952786c6d696c79c2dbc239dd4e91...,de88c121a82a06352bf1aaceba20578356408a334ba046...,6da43b944e494e885e69af021f93c6d9331c78aa228084...,f0b2a1d0db08cc64f85d74f1d15c2191e0e49039f4d8f2...,Kimberly
1,4fc82b26aecb47d2868c4efbe3581732a3e7cbcc6c2efb...,4284,89c7286890f7347ab235234e74d406596a127ae3679042...,1.02,4fc82b26aecb47d2868c4efbe3581732a3e7cbcc6c2efb...,58.0,58.0,6.84,6.60,3.90,4fc82b26aecb47d2868c4efbe3581732a3e7cbcc6c2efb...,de88c121a82a06352bf1aaceba20578356408a334ba046...,a83dd0ccbffe39d071cc317ddf6e97f5c6b1c87af91919...,bd4f4a250da88f87729febc739ae97f439a14f9d38f0e3...,Kimberly
2,e629fa6598d732768f7c726b4b621285f9c3b85303900a...,6006,89c7286890f7347ab235234e74d406596a127ae3679042...,1.50,e629fa6598d732768f7c726b4b621285f9c3b85303900a...,57.5,63.0,7.53,7.49,4.32,e629fa6598d732768f7c726b4b621285f9c3b85303900a...,c939327ca16dcf97ca32521d8b834bf1de16573d21deda...,333e0a1e27815d0ceee55c473fe3dc93d56c63e3bee2b3...,03c358cbd92e83278fd523f58dc6a9b4b198d00728af65...,Kimberly
3,4523540f1504cd17100c4835e85b7eefd49911580f8eff...,983,89c7286890f7347ab235234e74d406596a127ae3679042...,0.38,4523540f1504cd17100c4835e85b7eefd49911580f8eff...,60.8,61.0,4.66,4.65,2.83,4523540f1504cd17100c4835e85b7eefd49911580f8eff...,de88c121a82a06352bf1aaceba20578356408a334ba046...,333e0a1e27815d0ceee55c473fe3dc93d56c63e3bee2b3...,f0b2a1d0db08cc64f85d74f1d15c2191e0e49039f4d8f2...,Kimberly
4,9400f1b21cb527d7fa3d3eabba93557a18ebe7a2ca4e47...,11078,89c7286890f7347ab235234e74d406596a127ae3679042...,1.53,9400f1b21cb527d7fa3d3eabba93557a18ebe7a2ca4e47...,60.7,60.0,7.45,7.41,4.51,9400f1b21cb527d7fa3d3eabba93557a18ebe7a2ca4e47...,de88c121a82a06352bf1aaceba20578356408a334ba046...,3f39d5c348e5b79d06e842c114e6cc571583bbf44e4b0e...,03c358cbd92e83278fd523f58dc6a9b4b198d00728af65...,Kimberly
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40450,f4669b5848b66564f2317866860f9334ac63f29de3ed45...,921,5dd272b4f316b776a7b8e3d0894b37e1e42be3d5d3b204...,0.42,f4669b5848b66564f2317866860f9334ac63f29de3ed45...,60.5,59.0,4.79,4.83,2.91,f4669b5848b66564f2317866860f9334ac63f29de3ed45...,de88c121a82a06352bf1aaceba20578356408a334ba046...,333e0a1e27815d0ceee55c473fe3dc93d56c63e3bee2b3...,ef736c1f91cd1900c3d9cde925b1bf4f013adc0211a9ee...,Paris
40451,9185c0199efc6aea5b4a97414cd297ead29ad55edec2a7...,540,5dd272b4f316b776a7b8e3d0894b37e1e42be3d5d3b204...,0.30,9185c0199efc6aea5b4a97414cd297ead29ad55edec2a7...,61.9,58.0,4.31,4.28,2.66,9185c0199efc6aea5b4a97414cd297ead29ad55edec2a7...,de88c121a82a06352bf1aaceba20578356408a334ba046...,a9f51566bd6705f7ea6ad54bb9deb449f795582d6529a0...,03c358cbd92e83278fd523f58dc6a9b4b198d00728af65...,Paris
40452,fbed8c8d9adc6a3004f597f06166a4b2f4ad8ad948ee87...,7092,5dd272b4f316b776a7b8e3d0894b37e1e42be3d5d3b204...,1.24,fbed8c8d9adc6a3004f597f06166a4b2f4ad8ad948ee87...,62.6,54.0,6.84,6.88,4.29,fbed8c8d9adc6a3004f597f06166a4b2f4ad8ad948ee87...,388655e25e91872329272fc10128ef5354b3b19a05d7e8...,44bd7ae60f478fae1061e11a7739f4b94d1daf917982d3...,ef736c1f91cd1900c3d9cde925b1bf4f013adc0211a9ee...,Paris
40453,1726e8e229489b353e6007fac1dfffb5300a96bf6166cf...,3710,5dd272b4f316b776a7b8e3d0894b37e1e42be3d5d3b204...,0.71,1726e8e229489b353e6007fac1dfffb5300a96bf6166cf...,61.9,56.0,5.69,5.72,3.53,1726e8e229489b353e6007fac1dfffb5300a96bf6166cf...,4e3cfaa334cbafb57a399a98fad8d3812ece460018f457...,f67ab10ad4e4c53121b6a5fe4da9c10ddee905b978d378...,ef736c1f91cd1900c3d9cde925b1bf4f013adc0211a9ee...,Paris
40454,9d733392d362d5c6f1d9b9659b601c7d4b5a1c1c8df579...,456,5dd272b4f316b776a7b8e3d0894b37e1e42be3d5d3b204...,0.33,9d733392d362d5c6f1d9b9659b601c7d4b5a1c1c8df579...,61.9,54.3,4.45,4.47,2.76,9d733392d362d5c6f1d9b9659b601c7d4b5a1c1c8df579...,4e3cfaa334cbafb57a399a98fad8d3812ece460018f457...,6da43b944e494e885e69af021f93c6d9331c78aa228084...,ef736c1f91cd1900c3d9cde925b1bf4f013adc0211a9ee...,Paris

In [87]:
#junto la de la df_city con la de clarity


df_join2 = [df_city, di_clarity]
df_clarity = ft.reduce(lambda left, right: pd.merge(left, right, on='clarity_id'), df_join2)
df_clarity

,index_id,price,city_id,carat,index_id,depth,table,x,y,z,index_id,cut_id,color_id,clarity_id,city,clarity
0,5feceb66ffc86f38d952786c6d696c79c2dbc239dd4e91...,4268,89c7286890f7347ab235234e74d406596a127ae3679042...,1.21,5feceb66ffc86f38d952786c6d696c79c2dbc239dd4e91...,62.4,58.0,6.83,6.79,4.25,5feceb66ffc86f38d952786c6d696c79c2dbc239dd4e91...,de88c121a82a06352bf1aaceba20578356408a334ba046...,6da43b944e494e885e69af021f93c6d9331c78aa228084...,f0b2a1d0db08cc64f85d74f1d15c2191e0e49039f4d8f2...,Kimberly,VS2
1,4523540f1504cd17100c4835e85b7eefd49911580f8eff...,983,89c7286890f7347ab235234e74d406596a127ae3679042...,0.38,4523540f1504cd17100c4835e85b7eefd49911580f8eff...,60.8,61.0,4.66,4.65,2.83,4523540f1504cd17100c4835e85b7eefd49911580f8eff...,de88c121a82a06352bf1aaceba20578356408a334ba046...,333e0a1e27815d0ceee55c473fe3dc93d56c63e3bee2b3...,f0b2a1d0db08cc64f85d74f1d15c2191e0e49039f4d8f2...,Kimberly,VS2
2,f5ca38f748a1d6eaf726b8a42fb575c3c71f1864a81433...,11177,89c7286890f7347ab235234e74d406596a127ae3679042...,1.54,f5ca38f748a1d6eaf726b8a42fb575c3c71f1864a81433...,61.0,60.0,7.46,7.42,4.54,f5ca38f748a1d6eaf726b8a42fb575c3c71f1864a81433...,de88c121a82a06352bf1aaceba20578356408a334ba046...,44bd7ae60f478fae1061e11a7739f4b94d1daf917982d3...,f0b2a1d0db08cc64f85d74f1d15c2191e0e49039f4d8f2...,Kimberly,VS2
3,2858dcd1057d3eae7f7d5f782167e24b61153c01551450...,1549,89c7286890f7347ab235234e74d406596a127ae3679042...,0.52,2858dcd1057d3eae7f7d5f782167e24b61153c01551450...,61.9,55.0,5.15,5.18,3.20,2858dcd1057d3eae7f7d5f782167e24b61153c01551450...,4e3cfaa334cbafb57a399a98fad8d3812ece460018f457...,333e0a1e27815d0ceee55c473fe3dc93d56c63e3bee2b3...,f0b2a1d0db08cc64f85d74f1d15c2191e0e49039f4d8f2...,Kimberly,VS2
4,05ada863a4cf9660fd8c68e2295f1d35b2264815f5b605...,2671,89c7286890f7347ab235234e74d406596a127ae3679042...,0.70,05ada863a4cf9660fd8c68e2295f1d35b2264815f5b605...,62.0,56.0,5.71,5.74,3.55,05ada863a4cf9660fd8c68e2295f1d35b2264815f5b605...,4e3cfaa334cbafb57a399a98fad8d3812ece460018f457...,f67ab10ad4e4c53121b6a5fe4da9c10ddee905b978d378...,f0b2a1d0db08cc64f85d74f1d15c2191e0e49039f4d8f2...,Kimberly,VS2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40450,08b8747cf8808b5969f1f00356925723d7da69b644b160...,2721,5dd272b4f316b776a7b8e3d0894b37e1e42be3d5d3b204...,0.70,08b8747cf8808b5969f1f00356925723d7da69b644b160...,63.1,58.0,5.60,5.66,3.55,08b8747cf8808b5969f1f00356925723d7da69b644b160...,c939327ca16dcf97ca32521d8b834bf1de16573d21deda...,f67ab10ad4e4c53121b6a5fe4da9c10ddee905b978d378...,3f9db06236e9719b61c826b612b882fa702ec81574e44c...,Paris,VVS2
40451,b23817d57f94155839c28c035af4beec4f9ff547599c09...,1337,5dd272b4f316b776a7b8e3d0894b37e1e42be3d5d3b204...,0.44,b23817d57f94155839c28c035af4beec4f9ff547599c09...,59.6,59.0,4.98,4.99,2.97,b23817d57f94155839c28c035af4beec4f9ff547599c09...,388655e25e91872329272fc10128ef5354b3b19a05d7e8...,a9f51566bd6705f7ea6ad54bb9deb449f795582d6529a0...,3f9db06236e9719b61c826b612b882fa702ec81574e44c...,Paris,VVS2
40452,e09a3b3eef1e3a664f3fddbdf92208d8223db888f8151e...,3981,5dd272b4f316b776a7b8e3d0894b37e1e42be3d5d3b204...,0.81,e09a3b3eef1e3a664f3fddbdf92208d8223db888f8151e...,63.5,55.0,5.90,5.94,3.76,e09a3b3eef1e3a664f3fddbdf92208d8223db888f8151e...,388655e25e91872329272fc10128ef5354b3b19a05d7e8...,333e0a1e27815d0ceee55c473fe3dc93d56c63e3bee2b3...,3f9db06236e9719b61c826b612b882fa702ec81574e44c...,Paris,VVS2
40453,d739479786f64801f266489c09214d1f65aeefe7bc8795...,514,5dd272b4f316b776a7b8e3d0894b37e1e42be3d5d3b204...,0.28,d739479786f64801f266489c09214d1f65aeefe7bc8795...,61.2,55.0,4.18,4.22,2.57,d739479786f64801f266489c09214d1f65aeefe7bc8795...,4e3cfaa334cbafb57a399a98fad8d3812ece460018f457...,44bd7ae60f478fae1061e11a7739f4b94d1daf917982d3...,3f9db06236e9719b61c826b612b882fa702ec81574e44c...,Paris,VVS2
40454,39f0ab87faa547b2194fd6ed05b1bb35a64dc0d4c9ec52...,581,5dd272b4f316b776a7b8e3d0894b37e1e42be3d5d3b204...,0.30,39f0ab87faa547b2194fd6ed05b1bb35a64dc0d4c9ec52...,61.5,56.0,4.34,4.38,2.68,39f0ab87faa547b2194fd6ed05b1bb35a64dc0d4c9ec52...,4e3cfaa334cbafb57a399a98fad8d3812ece460018f457...,44bd7ae60f478fae1061e11a7739f4b94d1daf917982d3...,3f9db06236e9719b61c826b612b882fa702ec81574e44c...,Paris,VVS2

In [88]:
#junto la df_clarity con la de color

df_join3 = [df_clarity, di_color]
df_color = ft.reduce(lambda left, right: pd.merge(left, right, on='color_id'), df_join3)
df_color

,index_id,price,city_id,carat,index_id,depth,table,x,y,z,index_id,cut_id,color_id,clarity_id,city,clarity,color
0,5feceb66ffc86f38d952786c6d696c79c2dbc239dd4e91...,4268,89c7286890f7347ab235234e74d406596a127ae3679042...,1.21,5feceb66ffc86f38d952786c6d696c79c2dbc239dd4e91...,62.4,58.0,6.83,6.79,4.25,5feceb66ffc86f38d952786c6d696c79c2dbc239dd4e91...,de88c121a82a06352bf1aaceba20578356408a334ba046...,6da43b944e494e885e69af021f93c6d9331c78aa228084...,f0b2a1d0db08cc64f85d74f1d15c2191e0e49039f4d8f2...,Kimberly,VS2,J
1,ed053874ca199cc53e11c9f4aeaeccd07da652d1c19e3c...,3215,89c7286890f7347ab235234e74d406596a127ae3679042...,0.92,ed053874ca199cc53e11c9f4aeaeccd07da652d1c19e3c...,61.1,57.0,6.31,6.22,3.83,ed053874ca199cc53e11c9f4aeaeccd07da652d1c19e3c...,4e3cfaa334cbafb57a399a98fad8d3812ece460018f457...,6da43b944e494e885e69af021f93c6d9331c78aa228084...,f0b2a1d0db08cc64f85d74f1d15c2191e0e49039f4d8f2...,Kimberly,VS2,J
2,248aa2bdd0032920ac9e5f6ad36c350549da067efeaf7b...,4839,89c7286890f7347ab235234e74d406596a127ae3679042...,1.20,248aa2bdd0032920ac9e5f6ad36c350549da067efeaf7b...,60.8,60.0,6.85,6.89,4.18,248aa2bdd0032920ac9e5f6ad36c350549da067efeaf7b...,de88c121a82a06352bf1aaceba20578356408a334ba046...,6da43b944e494e885e69af021f93c6d9331c78aa228084...,f0b2a1d0db08cc64f85d74f1d15c2191e0e49039f4d8f2...,Kimberly,VS2,J
3,72b31cf00f8ab3967588fad4a32f61622cb162f9b7bc2c...,368,89c7286890f7347ab235234e74d406596a127ae3679042...,0.30,72b31cf00f8ab3967588fad4a32f61622cb162f9b7bc2c...,60.6,59.0,4.34,4.38,2.64,72b31cf00f8ab3967588fad4a32f61622cb162f9b7bc2c...,de88c121a82a06352bf1aaceba20578356408a334ba046...,6da43b944e494e885e69af021f93c6d9331c78aa228084...,f0b2a1d0db08cc64f85d74f1d15c2191e0e49039f4d8f2...,Kimberly,VS2,J
4,bc805497f86694cef2e1cf6df62989cb818f69a80f4fb1...,13542,89c7286890f7347ab235234e74d406596a127ae3679042...,2.00,bc805497f86694cef2e1cf6df62989cb818f69a80f4fb1...,58.0,62.0,8.17,8.25,4.76,bc805497f86694cef2e1cf6df62989cb818f69a80f4fb1...,c939327ca16dcf97ca32521d8b834bf1de16573d21deda...,6da43b944e494e885e69af021f93c6d9331c78aa228084...,f0b2a1d0db08cc64f85d74f1d15c2191e0e49039f4d8f2...,Kimberly,VS2,J
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40450,5eb1d62955a51a5ce396a89a9f2c111ef2df468b5450d7...,9897,5dd272b4f316b776a7b8e3d0894b37e1e42be3d5d3b204...,1.04,5eb1d62955a51a5ce396a89a9f2c111ef2df468b5450d7...,62.4,56.0,6.51,6.47,4.05,5eb1d62955a51a5ce396a89a9f2c111ef2df468b5450d7...,4e3cfaa334cbafb57a399a98fad8d3812ece460018f457...,a9f51566bd6705f7ea6ad54bb9deb449f795582d6529a0...,3f9db06236e9719b61c826b612b882fa702ec81574e44c...,Paris,VVS2,E
40451,8c8c8a435cae6ea17cb4ea2d8e8a25e7db1c765feeb2ae...,548,5dd272b4f316b776a7b8e3d0894b37e1e42be3d5d3b204...,0.25,8c8c8a435cae6ea17cb4ea2d8e8a25e7db1c765feeb2ae...,61.7,57.0,4.08,4.12,2.53,8c8c8a435cae6ea17cb4ea2d8e8a25e7db1c765feeb2ae...,388655e25e91872329272fc10128ef5354b3b19a05d7e8...,a9f51566bd6705f7ea6ad54bb9deb449f795582d6529a0...,3f9db06236e9719b61c826b612b882fa702ec81574e44c...,Paris,VVS2,E
40452,c564f3382889ba53b314960a2a53d414e082ffc997960c...,814,5dd272b4f316b776a7b8e3d0894b37e1e42be3d5d3b204...,0.30,c564f3382889ba53b314960a2a53d414e082ffc997960c...,60.7,55.0,4.35,4.36,2.65,c564f3382889ba53b314960a2a53d414e082ffc997960c...,388655e25e91872329272fc10128ef5354b3b19a05d7e8...,a9f51566bd6705f7ea6ad54bb9deb449f795582d6529a0...,3f9db06236e9719b61c826b612b882fa702ec81574e44c...,Paris,VVS2,E
40453,2cf5ed625832119319d1e63d0aebd4fe62825eda8cdf0e...,1013,5dd272b4f316b776a7b8e3d0894b37e1e42be3d5d3b204...,0.30,2cf5ed625832119319d1e63d0aebd4fe62825eda8cdf0e...,61.3,59.0,4.32,4.30,2.64,2cf5ed625832119319d1e63d0aebd4fe62825eda8cdf0e...,de88c121a82a06352bf1aaceba20578356408a334ba046...,a9f51566bd6705f7ea6ad54bb9deb449f795582d6529a0...,3f9db06236e9719b61c826b612b882fa702ec81574e44c...,Paris,VVS2,E
40454,b23817d57f94155839c28c035af4beec4f9ff547599c09...,1337,5dd272b4f316b776a7b8e3d0894b37e1e42be3d5d3b204...,0.44,b23817d57f94155839c28c035af4beec4f9ff547599c09...,59.6,59.0,4.98,4.99,2.97,b23817d57f94155839c28c035af4beec4f9ff547599c09...,388655e25e91872329272fc10128ef5354b3b19a05d7e8...,a9f51566bd6705f7ea6ad54bb9deb449f795582d6529a0...,3f9db06236e9719b61c826b612b882fa702ec81574e44c...,Paris,VVS2,E

In [89]:
# y finalmente junto la df_color con la de cut, con esta acabaríamos de juntarlas todas

df_join4 = [df_color, di_cut]
df_cut = ft.reduce(lambda left, right: pd.merge(left, right, on='cut_id'), df_join4)
df_cut

,index_id,price,city_id,carat,index_id,depth,table,x,y,z,index_id,cut_id,color_id,clarity_id,city,clarity,color,cut
0,5feceb66ffc86f38d952786c6d696c79c2dbc239dd4e91...,4268,89c7286890f7347ab235234e74d406596a127ae3679042...,1.21,5feceb66ffc86f38d952786c6d696c79c2dbc239dd4e91...,62.4,58.0,6.83,6.79,4.25,5feceb66ffc86f38d952786c6d696c79c2dbc239dd4e91...,de88c121a82a06352bf1aaceba20578356408a334ba046...,6da43b944e494e885e69af021f93c6d9331c78aa228084...,f0b2a1d0db08cc64f85d74f1d15c2191e0e49039f4d8f2...,Kimberly,VS2,J,Premium
1,248aa2bdd0032920ac9e5f6ad36c350549da067efeaf7b...,4839,89c7286890f7347ab235234e74d406596a127ae3679042...,1.20,248aa2bdd0032920ac9e5f6ad36c350549da067efeaf7b...,60.8,60.0,6.85,6.89,4.18,248aa2bdd0032920ac9e5f6ad36c350549da067efeaf7b...,de88c121a82a06352bf1aaceba20578356408a334ba046...,6da43b944e494e885e69af021f93c6d9331c78aa228084...,f0b2a1d0db08cc64f85d74f1d15c2191e0e49039f4d8f2...,Kimberly,VS2,J,Premium
2,72b31cf00f8ab3967588fad4a32f61622cb162f9b7bc2c...,368,89c7286890f7347ab235234e74d406596a127ae3679042...,0.30,72b31cf00f8ab3967588fad4a32f61622cb162f9b7bc2c...,60.6,59.0,4.34,4.38,2.64,72b31cf00f8ab3967588fad4a32f61622cb162f9b7bc2c...,de88c121a82a06352bf1aaceba20578356408a334ba046...,6da43b944e494e885e69af021f93c6d9331c78aa228084...,f0b2a1d0db08cc64f85d74f1d15c2191e0e49039f4d8f2...,Kimberly,VS2,J,Premium
3,98c53df687f2e9b94da80eef5b9049f1fac456b4c41c80...,5053,89c7286890f7347ab235234e74d406596a127ae3679042...,1.20,98c53df687f2e9b94da80eef5b9049f1fac456b4c41c80...,62.6,57.0,6.80,6.72,4.23,98c53df687f2e9b94da80eef5b9049f1fac456b4c41c80...,de88c121a82a06352bf1aaceba20578356408a334ba046...,6da43b944e494e885e69af021f93c6d9331c78aa228084...,f0b2a1d0db08cc64f85d74f1d15c2191e0e49039f4d8f2...,Kimberly,VS2,J,Premium
4,5dfe43a321c6834c7de273c73aeadc705d919a5869e0f5...,3593,89c7286890f7347ab235234e74d406596a127ae3679042...,1.05,5dfe43a321c6834c7de273c73aeadc705d919a5869e0f5...,59.4,62.0,6.66,6.58,3.93,5dfe43a321c6834c7de273c73aeadc705d919a5869e0f5...,de88c121a82a06352bf1aaceba20578356408a334ba046...,6da43b944e494e885e69af021f93c6d9331c78aa228084...,f0b2a1d0db08cc64f85d74f1d15c2191e0e49039f4d8f2...,Kimberly,VS2,J,Premium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40450,2e06d9b9fb5a84f3e7cc6f4ec05030c271772586527532...,586,6c425048aa7badd9d84615bd8620ca1864efd81cfdb69d...,0.30,2e06d9b9fb5a84f3e7cc6f4ec05030c271772586527532...,66.6,54.0,4.14,4.18,2.77,2e06d9b9fb5a84f3e7cc6f4ec05030c271772586527532...,f7b19afcde965ea4942b878d266f89f8ba9a5a833e60f7...,a9f51566bd6705f7ea6ad54bb9deb449f795582d6529a0...,3f9db06236e9719b61c826b612b882fa702ec81574e44c...,Dubai,VVS2,E,Fair
40451,8c0906fd5efd19b24aa04cb58ff5d90de07a4507ab1620...,5430,0013c01fe0d094209b8bd3d23b8f96dbabcd01ddd2a039...,0.91,8c0906fd5efd19b24aa04cb58ff5d90de07a4507ab1620...,63.1,55.0,6.13,6.00,3.83,8c0906fd5efd19b24aa04cb58ff5d90de07a4507ab1620...,f7b19afcde965ea4942b878d266f89f8ba9a5a833e60f7...,a9f51566bd6705f7ea6ad54bb9deb449f795582d6529a0...,3f9db06236e9719b61c826b612b882fa702ec81574e44c...,Amsterdam,VVS2,E,Fair
40452,9bbe997bfd8f696de7cd7c474dce9f4ce4d1f5df28f18b...,1705,0013c01fe0d094209b8bd3d23b8f96dbabcd01ddd2a039...,0.49,9bbe997bfd8f696de7cd7c474dce9f4ce4d1f5df28f18b...,65.5,58.0,4.91,4.86,3.20,9bbe997bfd8f696de7cd7c474dce9f4ce4d1f5df28f18b...,f7b19afcde965ea4942b878d266f89f8ba9a5a833e60f7...,a9f51566bd6705f7ea6ad54bb9deb449f795582d6529a0...,3f9db06236e9719b61c826b612b882fa702ec81574e44c...,Amsterdam,VVS2,E,Fair
40453,99c6a18e1b9cb1061de4826d1f6ccaf96d4de1126034a5...,5551,0013c01fe0d094209b8bd3d23b8f96dbabcd01ddd2a039...,0.90,99c6a18e1b9cb1061de4826d1f6ccaf96d4de1126034a5...,58.1,59.0,6.21,6.26,3.62,99c6a18e1b9cb1061de4826d1f6ccaf96d4de1126034a5...,f7b19afcde965ea4942b878d266f89f8ba9a5a833e60f7...,a9f51566bd6705f7ea6ad54bb9deb449f795582d6529a0...,3f9db06236e9719b61c826b612b882fa702ec81574e44c...,Amsterdam,VVS2,E,Fair
40454,e83f125b8f31fc57c87032f7c67df89883454a2df041f0...,2079,5dd272b4f316b776a7b8e3d0894b37e1e42be3d5d3b204...,0.52,e83f125b8f31fc57c87032f7c67df89883454a2df041f0...,57.2,64.0,5.27,5.36,3.04,e83f125b8f31fc57c87032f7c67df89883454a2df041f0...,f7b19afcde965ea4942b878d266f89f8ba9a5a833e60f7...,a9f51566bd6705f7ea6ad54bb9deb449f795582d6529a0...,3f9db06236e9719b61c826b612b882fa702ec81574e44c...,Paris,VVS2,E,Fair

In [90]:
df_cut.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 40455 entries, 0 to 40454
Data columns (total 18 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   index_id    40455 non-null  object
 1   price       40455 non-null  int64
 2   city_id     40455 non-null  object
 3   carat       40455 non-null  float64
 4   index_id    40455 non-null  object
 5   depth       40455 non-null  float64
 6   table       40455 non-null  float64
 7   x           40455 non-null  float64
 8   y           40455 non-null  float64
 9   z           40455 non-null  float64
 10  index_id    40455 non-null  object
 11  cut_id      40455 non-null  object
 12  color_id    40455 non-null  object
 13  clarity_id  40455 non-null  object
 14  city        40455 non-null  object
 15  clarity     40455 non-null  object
 16  color       40455 non-null  object
 17  cut         40455 non-null  object
dtypes: float64(6), int64(1), object(11)
memory usage: 5.9+ MB

In [91]:
#quitamos las columnas duplicadas como es el index_id

df = df_cut.T.drop_duplicates().T
df

,index_id,price,city_id,carat,depth,table,x,y,z,cut_id,color_id,clarity_id,city,clarity,color,cut
0,5feceb66ffc86f38d952786c6d696c79c2dbc239dd4e91...,4268,89c7286890f7347ab235234e74d406596a127ae3679042...,1.21,62.4,58.0,6.83,6.79,4.25,de88c121a82a06352bf1aaceba20578356408a334ba046...,6da43b944e494e885e69af021f93c6d9331c78aa228084...,f0b2a1d0db08cc64f85d74f1d15c2191e0e49039f4d8f2...,Kimberly,VS2,J,Premium
1,248aa2bdd0032920ac9e5f6ad36c350549da067efeaf7b...,4839,89c7286890f7347ab235234e74d406596a127ae3679042...,1.2,60.8,60.0,6.85,6.89,4.18,de88c121a82a06352bf1aaceba20578356408a334ba046...,6da43b944e494e885e69af021f93c6d9331c78aa228084...,f0b2a1d0db08cc64f85d74f1d15c2191e0e49039f4d8f2...,Kimberly,VS2,J,Premium
2,72b31cf00f8ab3967588fad4a32f61622cb162f9b7bc2c...,368,89c7286890f7347ab235234e74d406596a127ae3679042...,0.3,60.6,59.0,4.34,4.38,2.64,de88c121a82a06352bf1aaceba20578356408a334ba046...,6da43b944e494e885e69af021f93c6d9331c78aa228084...,f0b2a1d0db08cc64f85d74f1d15c2191e0e49039f4d8f2...,Kimberly,VS2,J,Premium
3,98c53df687f2e9b94da80eef5b9049f1fac456b4c41c80...,5053,89c7286890f7347ab235234e74d406596a127ae3679042...,1.2,62.6,57.0,6.8,6.72,4.23,de88c121a82a06352bf1aaceba20578356408a334ba046...,6da43b944e494e885e69af021f93c6d9331c78aa228084...,f0b2a1d0db08cc64f85d74f1d15c2191e0e49039f4d8f2...,Kimberly,VS2,J,Premium
4,5dfe43a321c6834c7de273c73aeadc705d919a5869e0f5...,3593,89c7286890f7347ab235234e74d406596a127ae3679042...,1.05,59.4,62.0,6.66,6.58,3.93,de88c121a82a06352bf1aaceba20578356408a334ba046...,6da43b944e494e885e69af021f93c6d9331c78aa228084...,f0b2a1d0db08cc64f85d74f1d15c2191e0e49039f4d8f2...,Kimberly,VS2,J,Premium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40450,2e06d9b9fb5a84f3e7cc6f4ec05030c271772586527532...,586,6c425048aa7badd9d84615bd8620ca1864efd81cfdb69d...,0.3,66.6,54.0,4.14,4.18,2.77,f7b19afcde965ea4942b878d266f89f8ba9a5a833e60f7...,a9f51566bd6705f7ea6ad54bb9deb449f795582d6529a0...,3f9db06236e9719b61c826b612b882fa702ec81574e44c...,Dubai,VVS2,E,Fair
40451,8c0906fd5efd19b24aa04cb58ff5d90de07a4507ab1620...,5430,0013c01fe0d094209b8bd3d23b8f96dbabcd01ddd2a039...,0.91,63.1,55.0,6.13,6.0,3.83,f7b19afcde965ea4942b878d266f89f8ba9a5a833e60f7...,a9f51566bd6705f7ea6ad54bb9deb449f795582d6529a0...,3f9db06236e9719b61c826b612b882fa702ec81574e44c...,Amsterdam,VVS2,E,Fair
40452,9bbe997bfd8f696de7cd7c474dce9f4ce4d1f5df28f18b...,1705,0013c01fe0d094209b8bd3d23b8f96dbabcd01ddd2a039...,0.49,65.5,58.0,4.91,4.86,3.2,f7b19afcde965ea4942b878d266f89f8ba9a5a833e60f7...,a9f51566bd6705f7ea6ad54bb9deb449f795582d6529a0...,3f9db06236e9719b61c826b612b882fa702ec81574e44c...,Amsterdam,VVS2,E,Fair
40453,99c6a18e1b9cb1061de4826d1f6ccaf96d4de1126034a5...,5551,0013c01fe0d094209b8bd3d23b8f96dbabcd01ddd2a039...,0.9,58.1,59.0,6.21,6.26,3.62,f7b19afcde965ea4942b878d266f89f8ba9a5a833e60f7...,a9f51566bd6705f7ea6ad54bb9deb449f795582d6529a0...,3f9db06236e9719b61c826b612b882fa702ec81574e44c...,Amsterdam,VVS2,E,Fair
40454,e83f125b8f31fc57c87032f7c67df89883454a2df041f0...,2079,5dd272b4f316b776a7b8e3d0894b37e1e42be3d5d3b204...,0.52,57.2,64.0,5.27,5.36,3.04,f7b19afcde965ea4942b878d266f89f8ba9a5a833e60f7...,a9f51566bd6705f7ea6ad54bb9deb449f795582d6529a0...,3f9db06236e9719b61c826b612b882fa702ec81574e44c...,Paris,VVS2,E,Fair

In [132]:
df_num = pd.DataFrame(df, columns=["price", "carat", "cut","color","clarity","depth", "table", "x", "y", "z","city"])
df_num["id"]= df_num["price"]
df_1 = df_num.drop(["clarity", "cut", "city", "price", "color"], axis=1)
df_1

      carat depth table     x     y     z    id
0      1.21  62.4  58.0  6.83  6.79  4.25  4268
1       1.2  60.8  60.0  6.85  6.89  4.18  4839
2       0.3  60.6  59.0  4.34  4.38  2.64   368
3       1.2  62.6  57.0   6.8  6.72  4.23  5053
4      1.05  59.4  62.0  6.66  6.58  3.93  3593
...     ...   ...   ...   ...   ...   ...   ...
40450   0.3  66.6  54.0  4.14  4.18  2.77   586
40451  0.91  63.1  55.0  6.13   6.0  3.83  5430
40452  0.49  65.5  58.0  4.91  4.86   3.2  1705
40453   0.9  58.1  59.0  6.21  6.26  3.62  5551
40454  0.52  57.2  64.0  5.27  5.36  3.04  2079

[40455 rows x 7 columns]

In [133]:
X=[["carat","clarity","depth", "table", "x", "y", "z"]]
y=["id"]

In [134]:
X, y = make_regression(n_samples=20000, n_features=10, random_state=42)
#X, y = datasets.load_diabetes(return_X_y=True)
print(X.shape, y.shape)

(20000, 10) (20000,)

In [135]:
# Train and test
# Train and test

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
print(f"X_train: {X_train.shape}, X_test: {X_test.shape}, y_train: {y_train.shape}, y_test: {y_test.shape}")
#print(f"X_train: {type(X_train)}, X_test: {type(X_test)}, y_train: {type(y_train)}, y_test: {type(y_test)}")

X_train: (16000, 10), X_test: (4000, 10), y_train: (16000,), y_test: (4000,)

In [136]:
%%time

# Model definition

model = linear_model.Lasso()
#model = ElasticNet()
#model = Ridge()
#model = SVR()
#model = SGDRegressor()
#model = LinearRegression()

hyperparameters = model.get_params()

print(type(model), '\n')
print('Model hyperparameters:', hyperparameters, '\n')

<class 'sklearn.linear_model._coordinate_descent.Lasso'>

Model hyperparameters: {'alpha': 1.0, 'copy_X': True, 'fit_intercept': True, 'max_iter': 1000, 'normalize': 'deprecated', 'positive': False, 'precompute': False, 'random_state': None, 'selection': 'cyclic', 'tol': 0.0001, 'warm_start': False}

CPU times: user 782 µs, sys: 1.21 ms, total: 1.99 ms
Wall time: 2.38 ms

In [148]:
X_train

array([[ 0.12333076,  1.47319151, -0.43058757, ...,  0.77489063,
         0.77716239,  0.61376599],
       [ 1.05704342, -1.82551211,  0.49243734, ...,  1.1847439 ,
         1.46420127, -0.69582995],
       [ 0.3653142 , -2.36505237,  0.54579218, ..., -1.46742143,
         0.02596154,  0.16557432],
       ...,
       [ 1.18673462, -0.71222076,  0.63866017, ...,  0.29815847,
         0.6032475 ,  1.43633541],
       [ 1.8635116 , -0.5457654 , -1.32379932, ..., -0.40741702,
        -0.17990973, -0.03681529],
       [ 1.97969028,  1.30082429,  1.13425682, ...,  0.14652807,
        -0.06378938,  1.03870608]])

In [137]:
%%time

# Model training

model.fit(X_train, y_train)

print('Model:', model, '\n')
print('Model hyperparameters:', hyperparameters, '\n')
print('Model coefficients:', model.coef_, '\n')

Model: Lasso()

Model hyperparameters: {'alpha': 1.0, 'copy_X': True, 'fit_intercept': True, 'max_iter': 1000, 'normalize': 'deprecated', 'positive': False, 'precompute': False, 'random_state': None, 'selection': 'cyclic', 'tol': 0.0001, 'warm_start': False}

Model coefficients: [23.62542958 84.40800669 97.88180809 35.29860875 34.69714098 93.69460271
  9.11528321 76.09939357 47.38945668 43.49030768]

CPU times: user 19.3 ms, sys: 14.8 ms, total: 34.1 ms
Wall time: 11.6 ms

In [138]:
%%time

# Model predictions

predictions = model.predict(X_test)

print(type(predictions))

<class 'numpy.ndarray'>
CPU times: user 1.53 ms, sys: 1.45 ms, total: 2.98 ms
Wall time: 1.62 ms

In [139]:
%%time

# Train the model and make predictions

regressor = LinearRegression()
#regressor = RandomForestRegressor()
hyperparameters = regressor.get_params()
regressor.fit(X_train, y_train)
y_pred = regressor.predict(X_test)

print('Model:', regressor, '\n')
print('Model hyperparameters:', hyperparameters, '\n')
#print('Model coefficients:', regressor.coef_, '\n')
#print('Model feature importance:', regressor.feature_importances_)
print('Ground truth target:', y_test, '\n')
print('Predicted target:', y_pred, '\n')

Model: LinearRegression()

Model hyperparameters: {'copy_X': True, 'fit_intercept': True, 'n_jobs': None, 'normalize': 'deprecated', 'positive': False}

Ground truth target: [-204.80972064 -129.50849927  -36.10897629 ... -280.72052786  323.24274467
  171.26373196]

Predicted target: [-204.80972064 -129.50849927  -36.10897629 ... -280.72052786  323.24274467
  171.26373196]

CPU times: user 19.2 ms, sys: 13.7 ms, total: 32.9 ms
Wall time: 17.7 ms

In [140]:
# MSE calculation

mean_squared_error(y_test, y_pred)

1.0474806188074424e-25

In [141]:
rmse = mean_squared_error(y_test, y_pred, squared=False)
rmse

3.236480524902695e-13

In [142]:
test_d = pd.read_csv("./data/diamonds_test.csv")
test_d.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13485 entries, 0 to 13484
Data columns (total 11 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   id       13485 non-null  int64
 1   carat    13485 non-null  float64
 2   cut      13485 non-null  object
 3   color    13485 non-null  object
 4   clarity  13485 non-null  object
 5   depth    13485 non-null  float64
 6   table    13485 non-null  float64
 7   x        13485 non-null  float64
 8   y        13485 non-null  float64
 9   z        13485 non-null  float64
 10  city     13485 non-null  object
dtypes: float64(6), int64(1), object(4)
memory usage: 1.1+ MB

In [143]:
test_d = test_d.drop(["color", "cut", "clarity", "city"], axis=1)
test_d

          id  carat  depth  table     x     y     z
0          0   0.79   62.7   60.0  5.82  5.89  3.67
1          1   1.20   61.0   57.0  6.81  6.89  4.18
2          2   1.57   62.2   61.0  7.38  7.32  4.57
3          3   0.90   63.8   54.0  6.09  6.13  3.90
4          4   0.50   62.9   58.0  5.05  5.09  3.19
...      ...    ...    ...    ...   ...   ...   ...
13480  13480   0.57   61.9   56.0  5.35  5.32  3.30
13481  13481   0.71   62.2   55.0  5.71  5.73  3.56
13482  13482   0.70   61.6   55.0  5.75  5.71  3.53
13483  13483   0.70   58.8   57.0  5.85  5.89  3.45
13484  13484   0.40   62.4   55.0  4.70  4.73  2.94

[13485 rows x 7 columns]

In [144]:
%%time

# Model predictions

predictions = model.predict(test_d)

print(type(predictions))

/Users/halimaelbadoui/miniconda3/envs/m3_hi/lib/python3.10/site-packages/sklearn/base.py:443: UserWarning: X has feature names, but Lasso was fitted without feature names
  warnings.warn(

ValueError: X has 7 features, but Lasso is expecting 10 features as input.